-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 5bf6c09bfa1297d3692cadd621ef95f1284e33c0
    hooks:
    -   id: debug-statements
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: flake8
        args:
        - --exclude=docs/*,*migrations*
        - --ignore=E501
